from pyautogui import*
from time import*
from random import*

kolishestvo_povtorov = (input("если введете цыфру то ето будет обозночять количество повторов если вы введете что то другое ето будент бесконечный"))
shetshik_edu = 0
shetshik_peredvegenia = 0

if  kolishestvo_povtorov.isdigit():
    for _ in range(2):
        print("1")
        dobavlenie_zaderhki = random()
        moveTo(1091 , 380 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(941 , 260 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(678 , 511 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(728 , 199 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(694 , 580 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(833 , 299 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(1351 , 599 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(1289 , 619 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        if shetshik_peredvegenia == 0:
            moveTo(900 , 685 , duration=1)
            click()
            sleep(3 + dobavlenie_zaderhki)
            moveTo(688 , 485 , duration=1)
            click()
            sleep(3 + dobavlenie_zaderhki)
            shetshik_peredvegenia += 1
        else:
            for _ in range(int(kolishestvo_povtorov)):
                dobavlenie_zaderhki = random()
                moveTo(1029 , 570 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(767 , 359 , duration=1)
                click()
                sleep(2 + dobavlenie_zaderhki)
                moveTo(839 , 540 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(762 , 205 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(627 , 553 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(885 , 309 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(1351 , 599 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(1289 , 619 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                print("1.1")
                shetshik_edu += 1
                print("количество повторов " , shetshik_edu , "еда будет проедина на 29 повтор")
                if shetshik_edu == 29:
                    press("f2")
                    sleep(dobavlenie_zaderhki)
                    shetshik_edu -= 29        
else:
    for _ in range(2):
        print("2")
        dobavlenie_zaderhki = random()
        moveTo(1091 , 380 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(941 , 260 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(678 , 511 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(728 , 199 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(694 , 580 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(833 , 299 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(1351 , 599 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        moveTo(1289 , 619 , duration=1)
        click()
        sleep(3 + dobavlenie_zaderhki)
        if shetshik_peredvegenia == 0:
            moveTo(900 , 685 , duration=1)
            click()
            sleep(3 + dobavlenie_zaderhki)
            moveTo(688 , 485 , duration=1)
            click()
            sleep(3 + dobavlenie_zaderhki)
            shetshik_peredvegenia += 1
        else:
            while True:
                dobavlenie_zaderhki = random()
                moveTo(1029 , 570 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(767 , 359 , duration=1)
                click()
                sleep(2 + dobavlenie_zaderhki)
                moveTo(839 , 540 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(762 , 205 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(627 , 553 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(885 , 309 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(1351 , 599 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                moveTo(1289 , 619 , duration=1)
                click()
                sleep(3 + dobavlenie_zaderhki)
                print("2.1")
                shetshik_edu += 1
                print("количество повторов " , shetshik_edu , "еда будет проедина на 29 повтор")
                if shetshik_edu == 29:
                    press("f2")
                    sleep(dobavlenie_zaderhki)
                    shetshik_edu -= 29
